name: flutter_dump_playground
description: "A diverse collection of samples and projects to boost your Flutter skills."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  moon_design: ^0.52.0

dev_dependencies:
  flakes: ^1.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
